# Use an official lightweight Python runtime as a parent image
FROM python:3.11-slim


# Install curl for health checks 
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE=1

# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED=1

# Set the working directory inside the container
WORKDIR /code

# Copy only the requirements file first to leverage Docker cache
COPY requirements.txt .

# Install dependencies without using the cache directory to save space
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application source code into the container
COPY app ./app

# Expose the port the app runs on 
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
